### ISSUE TITLE
Crash when run 'npm run start' Error: ENOENT: no such file or directory, open '.git-info'

### ISSUE THREAD

**Issue by WeyNiDrop** [hirosystems/ordinals-api#176]
**Describe the bug**

> @hirosystems/ordinals-api@1.0.0 start
> node dist/src/index.js

node:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, open '.git-info'
    at Object.openSync (node:fs:601:3)
    at readFileSync (node:fs:469:35)
    at getServerVersion (/home/evan/Desktop/ord/ordinals-api/node_modules/@hirosystems/api-toolkit/dist/server-version/index.js:13:57)
    at Object.<anonymous> (/home/evan/Desktop/ord/ordinals-api/node_modules/@hirosystems/api-toolkit/dist/server-version/index.js:16:26)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '.git-info'
}

**Desktop (please complete the following information):**
 - OS:  Ubuntu22.04 LTS
 - Node version: v18.16.0
 - ordinals-api version: lasted

**Comment by WeyNiDrop** [comment]
I went to the path of @hirosystems/api-toolkit/dist/server-version/ and I found there were two js file, index.js and git-info-generator.mjs, unfortunately, the git-info-generator.mjs is the function of generate .git-info file, but it was never been executed.

**Comment by rafaelcr** [comment]
@WeyNiDrop can you try 
```
npm run generate:git-info
```
before you try `start` again?

**Comment by WeyNiDrop** [comment]
Every time.

**Comment by WeyNiDrop** [comment]
> @WeyNiDrop can you try
> 
> ```
> npm run generate:git-info
> ```
> 
> before you try `start` again?

Its useful, thanks.

**Comment by smcclellan** [comment]
@WeyNiDrop Is this issue resolved from the above suggestion?

**Comment by WeyNiDrop** [comment]
> @WeyNiDrop Is this issue resolved from the above suggestion?

Yeah.

**Comment by chresko** [comment]
Can we close this?
