### ISSUE TITLE
ordinals-api v2.2.0 can't read body from the  ordhook v2.0.1

### ISSUE THREAD

**Issue by alexqrid** [hirosystems/ordinals-api#303]
**Describe the bug**
Hi! I've finally synced my `ordhook` indexer `v2.0.1` and it started to serve requests, unfortunately `ordinals-api v2.2.0` is not indexing the data from `ordhook` displaying the following error log:
<details><summary> ordinals-api log</summary

```json
  {
    "level": "info",
    "time": "2024-02-10T04:25:21.437Z",
    "pid": 7,
    "hostname": "dc6616b8b006",
    "name": "chainhook-client",
    "reqId": "req-2b",
    "req": {
      "method": "POST",
      "url": "/payload",
      "hostname": "ord-api:3099",
      "remoteAddress": "192.168.160.5",
      "remotePort": 47146
    },
    "msg": "incoming request"
  },
  {
    "level": "info",
    "time": "2024-02-10T04:25:21.437Z",
    "pid": 7,
    "hostname": "dc6616b8b006",
    "name": "chainhook-client",
    "reqId": "req-2b",
    "res": {
      "statusCode": 400
    },
    "err": {
      "type": "Error",
      "message": "body/apply/0/transactions/0/metadata must have required property 'description', body/apply/0/transactions/0/metadata/ordinal_operations/0/inscription_transferred must have required property 'ordinal_number', body/apply must match a schema in anyOf",
      "stack": "Error: body/apply/0/transactions/0/metadata must have required property 'description', body/apply/0/transactions/0/metadata/ordinal_operations/0/inscription_transferred must have required property 'ordinal_number', body/apply must match a schema in anyOf\n    at defaultSchemaErrorFormatter (/app/node_modules/fastify/lib/context.js:108:10)\n    at wrapValidationError (/app/node_modules/fastify/lib/validation.js:143:17)\n    at validate (/app/node_modules/fastify/lib/validation.js:123:12)\n    at preValidationCallback (/app/node_modules/fastify/lib/handleRequest.js:92:18)\n    at handler (/app/node_modules/fastify/lib/handleRequest.js:76:7)\n    at /app/node_modules/fastify/lib/contentTypeParser.js:192:9\n    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n    at done (/app/node_modules/fastify/lib/contentTypeParser.js:186:14)\n    at Parser.defaultJsonParser [as fn] (/app/node_modules/fastify/lib/contentTypeParser.js:292:5)\n    at IncomingMessage.onEnd (/app/node_modules/fastify/lib/contentTypeParser.js:271:27)",
      "statusCode": 400,
      "validation": [
        {
          "instancePath": "/apply/0/transactions/0/metadata",
          "schemaPath": "#/properties/apply/anyOf/0/items/properties/transactions/items/properties/metadata/required",
          "keyword": "required",
          "params": {
            "missingProperty": "description"
          },
          "message": "must have required property 'description'"
        },
        {
          "instancePath": "/apply/0/transactions/0/metadata/ordinal_operations/0/inscription_transferred",
          "schemaPath": "#/properties/apply/anyOf/1/items/properties/transactions/items/properties/metadata/properties/ordinal_operations/items/properties/inscription_transferred/required",
          "keyword": "required",
          "params": {
            "missingProperty": "ordinal_number"
          },
          "message": "must have required property 'ordinal_number'"
        },
        {
          "instancePath": "/apply",
          "schemaPath": "#/properties/apply/anyOf",
          "keyword": "anyOf",
          "params": {},
          "message": "must match a schema in anyOf"
        }
      ],
      "validationContext": "body"
    },
    "msg": "body/apply/0/transactions/0/metadata must have required property 'description', body/apply/0/transactions/0/metadata/ordinal_operations/0/inscription_transferred must have required property 'ordinal_number', body/apply must match a schema in anyOf"
  }

```

</details>

**To Reproduce**

Just try to sync from scratch.

**Expected behavior**
Everything is indexing without errors

**Additional context**
I'm running `ordinals-api`, `ordhook` using dockerfiles from the appropriate github repos.

**Comment by rafaelcr** [comment]
@alexqrid could you downgrade your API to v2.1.1? the version you're using expects ordhook v2.1.0 or higher

**Comment by smcclellan** [comment]
Closing for now. Please reopen if the above example does not help.

**Comment by alexqrid** [comment]
> @alexqrid could you downgrade your API to v2.1.1? the version you're using expects ordhook v2.1.0 or higher
Just bumped my ordhook and everything worked for a while, but then gap occured:

```json
{
   "level":"error",
   "time":"2024-02-27T09:38:22.096Z",
   "pid":7,
   "hostname":"5411191b0c81",
   "name":"chainhook-client",
   "err":{
      "type":"BadPayloadRequestError",
      "message":"Block inscription gap detected: Attempting to insert #35145006 (810990) but current max is #35144902. Chain tip is at 810985.",
      "stack":"BadPayloadRequestError: Block inscription gap detected: Attempting to insert #35145006 (810990) but current max is #35144902. Chain tip is at 810985.\n    at assertNoBlockInscriptionGap (/app/dist/src/pg/helpers.js:23:19)\n    at /app/dist/src/pg/pg-store.js:84:59\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async scope (/app/node_modules/postgres/cjs/src/index.js:226:18)\n    at async Function.begin (/app/node_modules/postgres/cjs/src/index.js:213:14)\n    at async PgStore.updateInscriptions (/app/dist/src/pg/pg-store.js:51:9)\n    at async /app/dist/src/ordhook/server.js:52:9\n    at async Object.<anonymous> (/app/node_modules/@hirosystems/chainhook-client/dist/server.js:177:17)",
      "name":"BadPayloadRequestError"
   },
   "msg":"ChainhookEventObserver bad payload"
}
```
Anyway it is not related to the issue, so, the issue resolved.
