### ISSUE TITLE
Indexing from scratch always detects gaps and stops

### ISSUE THREAD

**Issue by alexqrid** [hirosystems/ordinals-api#319]
Indexing from scratch always detects gaps, this seems to happen with all latest releases of `ordinals-api`. I've tried `v2.1.1` , `v2.2.0`, `v3.0.0`, and getting the same result at block height near `810k+-`:
```json
{
  "level": "error",
  "time": "2024-03-01T13:19:21.676Z",
  "pid": 7,
  "hostname": "bb4e651ca4a9",
  "name": "chainhook-client",
  "err": {
    "type": "BadPayloadRequestError",
    "message": "Block inscription gap detected: Attempting to insert #35144998 (810988) but current max is #35144902. Chain tip is at 810985.",
    "stack": "BadPayloadRequestError: Block inscription gap detected: Attempting to insert #35144998 (810988) but current max is #35144902. Chain tip is at 810985.\n    at assertNoBlockInscriptionGap (/app/dist/src/pg/helpers.js:23:19)\n    at /app/dist/src/pg/pg-store.js:85:59\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async scope (/app/node_modules/postgres/cjs/src/index.js:226:18)\n    at async Function.begin (/app/node_modules/postgres/cjs/src/index.js:213:14)\n    at async PgStore.updateInscriptions (/app/dist/src/pg/pg-store.js:52:9)\n    at async /app/dist/src/ordhook/server.js:57:9\n    at async Object.<anonymous> (/app/node_modules/@hirosystems/chainhook-client/dist/server.js:177:17)",
    "name": "BadPayloadRequestError"
  },
  "msg": "ChainhookEventObserver bad payload"
}
{
  "level": "info",
  "time": "2024-03-01T13:19:21.677Z",
  "pid": 7,
  "hostname": "bb4e651ca4a9",
  "name": "chainhook-client",
  "reqId": "req-51",
  "res": {
    "statusCode": 400
  },
  "responseTime": 116.15277099609375,
  "msg": "request completed"
}

{
  "level": "error",
  "time": "2024-03-01T13:19:21.676Z",
  "pid": 7,
  "hostname": "bb4e651ca4a9",
  "name": "chainhook-client",
  "err": {
    "type": "BadPayloadRequestError",
    "message": "Block inscription gap detected: Attempting to insert #35144998 (810988) but current max is #35144902. Chain tip is at 810985.",
    "stack": "BadPayloadRequestError: Block inscription gap detected: Attempting to insert #35144998 (810988) but current max is #35144902. Chain tip is at 810985.\n    at assertNoBlockInscriptionGap (/app/dist/src/pg/helpers.js:23:19)\n    at /app/dist/src/pg/pg-store.js:85:59\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async scope (/app/node_modules/postgres/cjs/src/index.js:226:18)\n    at async Function.begin (/app/node_modules/postgres/cjs/src/index.js:213:14)\n    at async PgStore.updateInscriptions (/app/dist/src/pg/pg-store.js:52:9)\n    at async /app/dist/src/ordhook/server.js:57:9\n    at async Object.<anonymous> (/app/node_modules/@hirosystems/chainhook-client/dist/server.js:177:17)",
    "name": "BadPayloadRequestError"
  },
  "msg": "ChainhookEventObserver bad payload"
}
{
  "level": "info",
  "time": "2024-03-01T13:19:21.677Z",
  "pid": 7,
  "hostname": "bb4e651ca4a9",
  "name": "chainhook-client",
  "reqId": "req-51",
  "res": {
    "statusCode": 400
  },
  "responseTime": 116.15277099609375,
  "msg": "request completed"
}

```

**Comment by rafaelcr** [comment]
@alexqrid can you share more details about the ordhook setup you have? there could be a version mismatch between the two

**Comment by rafaelcr** [comment]
Closing this, please reopen if you have any more questions
